name: ieeg
channels:
  - defaults
dependencies:
  - python<3.12
  - pip
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - cython
  - pandas
  - joblib
  - tqdm
  - notebook
  - pip:
    - -r requirements.txt